# Generated by Django 4.2.6 on 2023-10-06 17:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PVPGameStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_date', models.DateTimeField(auto_now_add=True, verbose_name='Date of the game')),
                ('loser', models.ManyToManyField(blank=True, null=True, related_name='loser', to=settings.AUTH_USER_MODEL, verbose_name='Game loser')),
                ('player1', models.ManyToManyField(related_name='player1', to=settings.AUTH_USER_MODEL, verbose_name='Player 1')),
                ('player2', models.ManyToManyField(related_name='player2', to=settings.AUTH_USER_MODEL, verbose_name='Player 2')),
                ('winner', models.ManyToManyField(blank=True, null=True, related_name='winner', to=settings.AUTH_USER_MODEL, verbose_name='Game winner')),
            ],
            options={
                'verbose_name': 'Game statistics',
                'verbose_name_plural': 'Games statistics',
            },
        ),
        migrations.CreateModel(
            name='PVCGameStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_date', models.DateTimeField(auto_now_add=True, verbose_name='Date of the game')),
                ('is_winner', models.BooleanField(verbose_name='Game winner')),
                ('player', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Player')),
            ],
            options={
                'verbose_name': 'PvC game statistics',
                'verbose_name_plural': 'PvC games statistics',
            },
        ),
    ]
