# Generated by Django 4.2.6 on 2023-10-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
        ('game', '0002_alter_pvcgamestats_player_alter_pvpgamestats_loser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pvpgamestats',
            name='loser',
            field=models.ManyToManyField(blank=True, related_name='loser', to='user_profile.user', verbose_name='Game loser'),
        ),
        migrations.AlterField(
            model_name='pvpgamestats',
            name='winner',
            field=models.ManyToManyField(blank=True, related_name='winner', to='user_profile.user', verbose_name='Game winner'),
        ),
    ]
