# Generated by Django 4.2.6 on 2023-11-12 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_pvpgamestats_loser_alter_pvpgamestats_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pvpgamestats',
            name='player1',
        ),
        migrations.RemoveField(
            model_name='pvpgamestats',
            name='player2',
        ),
    ]
